[server]
headless = true
port = 8501
enableCORS = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#7B61FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#2C2C2C"
font = "sans serif"