apiVersion: v1
kind: Service
metadata:
  name: rakshak-service
  labels:
    app: rakshak
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8501
      protocol: TCP
  selector:
    app: rakshak